/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './js/**/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  // Keep dynamic class fragments that may be toggled in JS
  safelist: [
    'hidden',
    'flex',
    'block',
    'bg-emerald-400',
    'bg-emerald-500',
    'bg-amber-400',
    'text-black',
    'border-emerald-400',
    'border-red-400',
    'border-blue-400',
    'border-purple-400',
    'bg-red-500/10',
    'bg-blue-500/10',
    'bg-purple-500/10',
    'bg-emerald-900/30',
    'bg-white/10',
    'text-white',
    'text-emerald-200',
    'text-red-400',
    'text-amber-400',
    'text-emerald-400',
    'text-yellow-300',
    'ring-1',
    'ring-red-400',
    'border-red-500',
    'from-[#fcd34d]',
    'to-[#f59e0b]',
    'bg-gradient-to-r',
    'active',
    'selected',
    'show',
    'reached',
  ],
}
